[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "retina-seg"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "opencv-python",
    "scikit-image",
    "scikit-learn",
    "imbalanced-learn",
    "numpy",
    "matplotlib",
    "streamlit",
    "joblib",
    "Pillow",
    "scipy",
    "pandas",
]

[tool.setuptools.packages.find]
where = ["src"]
